### ISSUE TITLE
Adding essentials home import

### ISSUE THREAD

**Issue by hwalker928** [ZamponiMarco/SpawnMe#1]
I think it would be cool to import essentials homes directly into this plugin.

**Comment by ZamponiMarco** [comment]
It's a really cool suggestion
Just not to misunderstand and do messes, can you please write here the link to the essentials plugin on spigot here?

**Comment by hwalker928** [comment]
Hey there!

I've worked with the essentials API before so if you need any help hmu on
discord harrydev#9999

The plugin page is https://essentialsx.net/

~harrydev
